# Generated by Django 2.2.1 on 2019-06-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=25)),
                ('designation', models.CharField(max_length=25)),
                ('Basic', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='esal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_id', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=50)),
                ('Basic', models.FloatField(max_length=15)),
                ('DA', models.FloatField()),
                ('TA', models.FloatField()),
                ('HRA', models.FloatField()),
                ('Special_allowance', models.FloatField()),
                ('PF', models.FloatField()),
                ('Pension', models.FloatField()),
                ('Insurence', models.FloatField()),
                ('ESI', models.FloatField()),
                ('Gross_Sal', models.FloatField()),
                ('Net_Sal', models.FloatField()),
                ('leaves_taken', models.FloatField()),
                ('total_workingdays', models.FloatField()),
                ('lop', models.FloatField()),
            ],
        ),
    ]
